### ISSUE TITLE
Disable lintr warnings dependent on packages

### ISSUE THREAD

**Issue by josephguillaume** [josephguillaume/hydromad#105]
Alternatively, move back to installing hydromad and dependencies

**Comment by josephguillaume** [comment]
> ##[warning]no visible global function definition for

**Comment by josephguillaume** [comment]
@mortisflux - it might be easiest for you to deal with this one too, if you tackle #102 

I think we go with skipping these checks, because R cmd check does them too.

**Comment by mortisflux** [comment]
From what I've seen, this can be disabled as per this [link](
https://github.com/REditorSupport/atom-ide-r/issues/7). So long as R CMD Check is also flagging these problems, it might be ok to disable `object_usage_linter.`

**Comment by josephguillaume** [comment]
Warning disabled in #116. I think this is the right thing to do, but this issue can be reopened if it turns out there are issues not covered by R CMD CHECK
