### ISSUE TITLE
Fix warning in README

### ISSUE THREAD

**Issue by josephguillaume** [josephguillaume/hydromad#114]
> #> Warning in zoo(rval[i], index(x)[i]): some methods for "zoo" objects do not work
> #> if the index entries in 'order.by' are not unique
> #> Warning in as.zooreg.zoo(newdata): 'x' does not have an underlying regularity

Sounds like there's a problem with the date column

**Comment by WillemVervoort** [comment]
In the Cotter data? I can have a look

**Comment by WillemVervoort** [comment]
It is odd:
> length(unique(time(Cotter[1:1000])))
[1] 1000
Seems ok

**Comment by WillemVervoort** [comment]
It is really weird, the error does not occur running the commands in R, so it is in the rendering? But that would mean hydromad that is loaded in the yaml is different from my installed version, or has zoo changed? The timeseries looks fine in the data

**Comment by josephguillaume** [comment]
Oh. Yes, it is probably the wrong version of hydromad. Because you're pulling from hydromad.catchment.org it doesn't have the fix for https://github.com/josephguillaume/hydromad/issues/23. I have no idea what data it's actually using then.
We should actually be building the package from github directly...

**Comment by WillemVervoort** [comment]
I think we can take a short cut on this. I don't think it is possible to build the package from github directly as that would involve devtools and this requires Rtools, which I can't find any evidence that this would be possible.
However a quick fix on the problem is to just insert "warnings = F" in the markdown R code block. I will do that now and add a PR

**Comment by WillemVervoort** [comment]
Can be closed, it seems #146 has fixed this

**Comment by josephguillaume** [comment]
Thanks Willem. 
In retrospect it's the right thing to build the README from the published stable package.
