### ISSUE TITLE
Add KGE objective function

### ISSUE THREAD

**Issue by buzacott** [josephguillaume/hydromad#125]
Minor enhancement to add the KGE objective function to `R/hydromad.stats.R` and description in `man/hydromad.stats.Rd`.

**Comment by josephguillaume** [comment]
That would be great. Are you happy to do a PR?

This is probably worth doing before the bigger solution of linking to other packages: https://github.com/josephguillaume/hydromad/issues/87

**Comment by buzacott** [comment]
I agree. Don't know if it will interfere with the roxygen PR but in any case that can be re-run for the .Rd file in question

#46  I was hoping to have in before the change, however with the other issues surrounding C/C++ maybe it is best to wait?
