### ISSUE TITLE
Tests failing due to C exports

### ISSUE THREAD

**Issue by mortisflux** [josephguillaume/hydromad#128]
# Issue: exporting C with R

## Issue summary:
The tests in #126 are failing because roxygen2 requires the use of `@useDynLib` tags to export C functions with R, and I haven't been able to get these to work.

## Current Behavior
Let's take `ar1_tv` from `filters.c`:

```
void ar1_tv(double *x, double *a, int *n, double *init, double *out) {
  int i;
  double tmp;
  tmp = *init;
  for (i = 0; i < *n; i++) {
    out[i] = x[i] + a[i] * tmp;
    tmp = out[i];
  }
}
```

I've been following [https://r-pkgs.org/src.html#clang](https://r-pkgs.org/src.html#clang) to export this using:

```
#' @useDynLib hydromad ar1_tv
ar1_tv <- function(x, a, n, init, out) {
  .C(ar1_tv,
     as.double(x),
     as.double(a),
     as.integer(n),
     as.double(init),
     as.double(out),
     NAOK = FALSE,
     PACKAGE = "hydromad"
  )
}
```

Calling `roxygen2::roxygenise()` exports this to NAMESPACE as `useDynLib(hydromad,ar1_tv)`, which seems correct. However, when I run devtools::check() I end up with this error message:

```
Error: package or namespace load failed for ‘hydromad’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/private/var/folders/sb/q56lv8011n78988rpzppr6gw0000gn/T/RtmpeLAahG/hydromad.Rcheck/00LOCK-hydromad/00new/hydromad/libs/hydromad.so':
  dlopen(/private/var/folders/sb/q56lv8011n78988rpzppr6gw0000gn/T/RtmpeLAahG/hydromad.Rcheck/00LOCK-hydromad/00new/hydromad/libs/hydromad.so, 6): Symbol not found: __hydromad_simhyd_sim
  Referenced from: /private/var/folders/sb/q56lv8011n78988rpzppr6gw0000gn/T/RtmpeLAahG/hydromad.Rcheck/00LOCK-hydromad/00new/hydromad/libs/hydromad.so
  Expected in: flat namespace
 in /private/var/folders/sb/q56lv8011n78988rpzppr6gw0000gn/T/RtmpeLAahG/hydromad.Rcheck/00LOCK-hydromad/00new/hydromad/libs/hydromad.so
Error: loading failed
Execution halted
ERROR: loading failed
```

My knowledge of C is limited, but it looks like R is looking for an .so file, which is a compiled file unless I'm mistaken. However, 'hydromad.so' doesn't match the name of any files currently in /src (i.e. there is no hydromad.c). Any help would be appreciated.

**Comment by jnothman** [comment]
The .so is not, in this case, compiled to /src. It's been compiled to `/private/var/folders/sb/q56lv8011n78988rpzppr6gw0000gn/T/RtmpeLAahG/hydromad.Rcheck/00LOCK-hydromad/00new/hydromad/libs/hydromad.so` during the check.

For some reason, it expects `__hydromad_simhyd_sim` to be available in the .so (i.e. that should be a name "exported" by the shared object), but it is not present.

Could you share a branch where the code is setup such that running `devtools::check()` would reproduce this issue?

**Comment by jnothman** [comment]
To be sure, it has no complaints about the .so before the roxygen change?

**Comment by jnothman** [comment]
I think this is the source of the issue:
https://github.com/josephguillaume/hydromad/pull/126/files#diff-7347fe5a0f184f79ef064e92e3beb297L313

In master we have:
https://github.com/josephguillaume/hydromad/blob/a6d195791d928f1821c5b50626e2a78f289554a7/NAMESPACE#L313
and
https://github.com/josephguillaume/hydromad/blob/f19832e5a38bdf4057e7313febf328f2a2ae8a4f/src/hydromad-init.c#L61-L63
and
https://github.com/josephguillaume/hydromad/blob/f19832e5a38bdf4057e7313febf328f2a2ae8a4f/src/hydromad-init.c#L40-L42

I'm not sure where that `_hydromad_simhyd_sim` is then used... Others may be able to advise on whether simply removing the code from hydromad-init.c could work.

**Comment by WillemVervoort** [comment]
Hi all,
I am not sure I understand enough, but could this arise from simhyd.ccp:
https://github.com/josephguillaume/hydromad/blob/master/src/simhyd.cpp
This might be the origin of __hydromad_simhyd_sim
Maybe because it uses .cpp rather than .c?

Willem

**Comment by jnothman** [comment]
I think that's the origin of it, but ... where is it used currently?

**Comment by WillemVervoort** [comment]
Aah yes, that could be an incomplete loose end. The compiled version is
supposed to run in
https://github.com/josephguillaume/hydromad/blob/master/R/simhyd.R
But in my original code I compiled from .ccp using Rccp, I am not sure how
this would work in the package (sorry beyond my paygrade).

Willem

**Comment by mortisflux** [comment]
> To be sure, it has no complaints about the .so before the roxygen change?

The R CMD check log from a previous PR ( [https://github.com/josephguillaume/hydromad/runs/864046192?check_suite_focus=true](https://github.com/josephguillaume/hydromad/runs/864046192?check_suite_focus=true) ) mentions hydromad.so in two places:

```
##[warning]File ‘hydromad/libs/hydromad.so’:
  Found ‘__printf_chk’, possibly from ‘printf’ (C)
    Object: ‘fland1.o’
  Found ‘exit’, possibly from ‘exit’ (C)
    Object: ‘fland1.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs.
```


```
checking compiled code ... WARNING
  File ‘hydromad/libs/hydromad.so’:
    Found ‘__printf_chk’, possibly from ‘printf’ (C)
      Object: ‘fland1.o’
    Found ‘exit’, possibly from ‘exit’ (C)
      Object: ‘fland1.o’
  
  Compiled code should not call entry points which might terminate R nor
  write to stdout/stderr instead of to the console, nor use Fortran I/O
  nor system RNGs.
  
  See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
```

There are no complaints about __hydromad_simhyd_sim though.

**Comment by mortisflux** [comment]
> Could you share a branch where the code is setup such that running `devtools::check()` would reproduce this issue?

I've created a branch called roxygen2_c_exports that is currently producing the error locally.

**Comment by jnothman** [comment]
So I think dropping that reference to simhyd_sim, and even the implementation, might be fine for now, @mortisflux.

**Comment by buzacott** [comment]
I think we want both C/C++ compatibility, as any models included in the future will likely be written in Rcpp (such as my HBV model I have already written...)

https://stackoverflow.com/questions/54000015/r-package-with-both-c-and-cpp-files-with-rcpp

I think that is the way to go^. If we wrap the C calls with Rcpp, it can compile all the attributes and we don't have to do anything messy by hand with `Hydromad-init.c` anymore. I've done some limited testing and I'm not getting any errors with simhyd anymore, but obviously the C stuff is broken.

I'll see how much effort it will be to make the Rcpp wrappers

**Comment by buzacott** [comment]
This is a bit trickier than I initially thought. I would think to skip it for now but in the future it would be nice if we could have Rcpp handle the glue.

@mortisflux did you have any luck with dropping the reference to simhyd_sim? I'll need to know as I'll run into the same issues with HBV

**Comment by buzacott** [comment]
A much simpler solution, just add:

`#' @useDynLib hydromad _hydromad_simhyd_sim`

After devtools::document(), it adds it to the namespace and no issues compiling the package. I added in some of the others back (e.g. #' @useDynLib hydromad sma_gr4j) and it is still all good.

I think the issue stems from `Rcpp::compileAttributes` automatically exports _hydromad_simhyd_sim, but perhaps it conflicts with `hydromad-init.c`

**Comment by mortisflux** [comment]
Thanks for your work @buzacott, will add the rest of the tags today and see how the tests / checks go.

**Comment by mortisflux** [comment]
@buzacott Curiously, after merging your branch into mine `devtools::check()` is returning the same error I was getting yesterday. I tried to apply the changes to the SIH roxygen2_documentation_v2 branch to see whether the same thing would happen, and it's yielding the same error.

On a related note, even when we have `#' @useDynLib hydromad _hydromad_simhyd_sim`, in simhyd.R, running `devtools::test()` yields:

```
test-sma-sim.R:113: error: simhyd simulation is the same in R and C
could not find function "simhyd_sim" 
```
Though I think this is because my R Studio is still having trouble with the simhyd export rather than anything else ...

**Comment by buzacott** [comment]
I must admit I didn't run `devtools::check()`. I only checked to see if the package would compile and I ran the models.

I got the same error as you when running the check, however try this:

```r
#' @useDynLib hydromad _hydromad_simhyd_sim
#' @useDynLib hydromad
#' @importFrom Rcpp sourceCpp
```

That fixed the simhyd error for me, but I'm getting some other ones because I didn't export all the C objects.

**Comment by mortisflux** [comment]
That did the trick! The function seems to be exporting fine now and devtools::check() runs properly, albeit with other unrelated errors which I'll get onto fixing now.

I've exported the other C objects on my end so `devtools::test()` isn't returning the previous errors 😄

**Comment by josephguillaume** [comment]
All good now :-)
