### ISSUE TITLE
R CMD check warning: stats:::tsdiag.Arima

### ISSUE THREAD

**Issue by mortisflux** [josephguillaume/hydromad#134]
# Issue: warning arising from stats:::tsdiag.Arima

## Issue summary:
R CMD check is currently returning the following warning:

```
W  checking dependencies in R code (1.8s)
   Unexported object imported by a ':::' call: ‘stats:::tsdiag.Arima’
     See the note in ?`:::` about the use of this operator.
     Including base/recommended package(s):
     ‘stats’
```

`tsdiag.Arima` is an internal function from `stats` so it can't be called using `::`, however, R CMD check discourages the use of `:::` calls and returns a warning call.

## Possible Solutions
1. Ask the developers of `stats` to expose this function.
2. Bring `tsdiag.Arima` into hydromad as a private utility function.
3. Cast object as a `stats::arima` before applying `tsdiag`.

**Comment by josephguillaume** [comment]
1. is probably not doable given it's increasingly encouraged to not export the methods for S3 generics
2. Seems redundant given that stats is a default installed package in hydromad
3. Seems over the top given that the function seems to run fine on an object that is (it seems) an invalid arima object.

So what we need to do is to be able to call the S3 generic method using a public interface. There's two options here:
4. Load the method explicitly using `getS3method("tsdiag","Arima")`
5. Use `class(object)<-"Arima"` to trick the S3 generic into firing even though other Arima functions probably wouldn't run successfully. This is a bit like an ugly manual cast.

Both solutions are ugly TBH, and are simply alternative ways of calling the non-exported S3 generic method (probably with some overhead, albeit unimportant here), but I suppose if CRAN asks for it...
