### ISSUE TITLE
 R CMD check: there are ::: calls to the package's namespace in its code

### ISSUE THREAD

**Issue by mortisflux** [josephguillaume/hydromad#136]
# ::: calls to the package's namespace in its code

## Issue summary:
R CMD check returns a note on the following:

```
 There are ::: calls to the package's namespace in its code. A package
  almost never needs to use ::: for its own objects:
  ‘update.hydromad’
```

The culprit seems to be the quote() line within update.hydromad.R in this block:

```
      ccall <- match.call()
      ccall[[1]] <- quote(hydromad:::update.hydromad)
      ccall <- as.call(modifyList(
        as.list(ccall),
        as.list(newpars)
      ))
```

## Current Behavior
Removing `:::` from the above satisfies R CMD check, however, `update.hydromad` isn't found when devtools::check is run on the examples that do require this function. For example, R CMD check stalls when checking bucket.Rd (when `:::` is removed ):

```
   > ## show effect of increase/decrease in each parameter
   > parRanges <- hydromad.getOption("bucket")
   > parsims <- mapply(
   +   val = parRanges, nm = names(parRanges),
   +   FUN = function(val, nm) {
   +     lopar <- min(val)
   +     hipar <- max(val)
   +     names(lopar) <- names(hipar) <- nm
   +     fitted(runlist(
   +       decrease = update(mod1, newpars = lopar),
   +       increase = update(mod1, newpars = hipar)
   +     ))
   +   }, SIMPLIFY = FALSE
   + )
   Error in update.hydromad(object = mod1, Sb = 0.1) : 
     could not find function "update.hydromad"
   Calls: mapply ... update -> update.hydromad -> eval.parent -> eval -> eval
```

I was considering skipping examples that need `update.hydromad` to force a green tick in the checks, but as there are a fair number of examples that require `update.hydromad`, it probably makes more sense to fix this rather than comment out each example that is stalling the check. R shouldn't have trouble finding functions from it's own package and using getAnywhere() manages to find the function.

**Comment by jnothman** [comment]
I think is about the use of `quote` and `eval.parent`. Since it's evaluating in the parent scope, `update.hydromad` is no longer being evaluated within the hydromad package. This might not be the ideal way to do it, but I think this usage is valid. Do "Notes" such as this actually fail R CMD check run? Is there a way to tell R CMD check that we are sure this is the way we want it done and the note should be disabled?

**Comment by jnothman** [comment]
In http://r-pkgs.had.co.nz/check.html they say "NOTEs: Mild problems. If you are submitting to CRAN, you should strive to eliminate all NOTEs, even if they are false positives." But how do you mark something as a false positive?

**Comment by mortisflux** [comment]
That link also states: "If it’s not possible to eliminate a NOTE, you’ll need describe why it’s OK in your submission comments, as described in release notes."

[https://www.rdocumentation.org/packages/devtools/versions/2.3.0/topics/check](https://www.rdocumentation.org/packages/devtools/versions/2.3.0/topics/check) says: "Passing R CMD check is essential if you want to submit your package to CRAN: you must not have any ERRORs or WARNINGs, and you want to ensure that there are as few NOTEs as possible. If you are not submitting to CRAN, at least ensure that there are no ERRORs or WARNINGs: these typically represent serious problems."

So it seems like CRAN may accept Notes if you can explain why you think the function causing a note is valid. I haven't been able to find anything on flagging Notes as false positives though ...

**Comment by mortisflux** [comment]
[http://r-pkgs.had.co.nz/release.html](http://r-pkgs.had.co.nz/release.html) says something similar too:

"Check results: I always state that there were no errors or warnings. Any NOTEs go in a bulleted list. For each NOTE, I include the message from R CMD check and a brief description of why I think it’s OK. If there were no NOTEs, I’d say “There were no ERRORs, WARNINGs or NOTEs” "

**Comment by josephguillaume** [comment]
Actually, I think the correct fix is to use `ccall[[1]] <- quote(update)`
`eval.parent` with `update` should correctly dispatch to the S3 method `update.hydromad` anyway

However, `update.hydromad` is a core function in hydromad - it's responsible for actually running models and storing results, so we'd want to make sure this is 100% correct.

**Comment by mortisflux** [comment]
Adding your fix got rid of the Note, @josephguillaume. I've run `devtools::test` and the tests involving `update` don't appear to throw related errors (test-statistics.R and test-with-exact-inputs.R), other than a warning for "SMA joint fitting methods work with exact inputs" which resulted in this:

```
test-with-exact-inputs.R:26: warning: rfit methods work on (2,1) model with exact inputs
did not converge after 12 iterations
```
When I run `fits <- runlist()` within test-with-exact-inputs.R:26:

```
Warning message:
In do_srivfit(DATA, init.model = init.model, order = order, noise.order = noise.order,  :
  did not converge after 12 iterations
```

However, the same error pops up in another branch that doesn't have the updated version of the code, so I don't think it is the change to `quote(update)` that is causing this.

**Comment by josephguillaume** [comment]
Thanks! Let's merge that it in then.
I would expect this change to raise errors if it wasn't right - the wrong S3 method for update would be dispatched and most subsequent functions would fail as a result.
