### ISSUE TITLE
Files in the 'vignettes' directory but no files in 'inst/doc'

### ISSUE THREAD

**Issue by mortisflux** [josephguillaume/hydromad#140]
# Issue: Files in the 'vignettes' directory but no files in 'inst/doc'

## Issue summary:
R CMD check issues the following warning for the roxygen2_documentation_v2 branch:

```
❯ checking files in ‘vignettes’ ... WARNING
  Files in the 'vignettes' directory but no files in 'inst/doc':
    ‘figures/ihacres_framework.png’, ‘hydromad.Rmd’
  Package has no Sweave vignette sources and no VignetteBuilder field.
```

Adding `knitr` to 'Suggests' and stating `VignetteBuilder: knitr` in `DESCRIPTION` seems to resolve this issue locally, so I'll make a PR to fix this.

**Comment by josephguillaume** [comment]
That should be fine - I believe this error is because @buzacott used knitr for the new website.

The current vignette is not building and will probably need to be replaced with something using knitr too, so this will be a forward compatible change.

**Comment by WillemVervoort** [comment]
The vignette rewrite using knitr would be a perfect job for me
Willem

**Comment by buzacott** [comment]
@WillemVervoort do you want me to send you my partially completed conversion of the sweave tutorial to Rmd?

From memory it is half to 2/3 completed

**Comment by WillemVervoort** [comment]
yes @buzacott that would be great
Willem

**Comment by josephguillaume** [comment]
Thanks @WillemVervoort and @buzacott 
Note that in the longer term we might want to revisit what the tutorial looks like, given the feedback received over the years.
Converting to Rmd will still be useful in the first instance though.
