### ISSUE TITLE
R CMD check failing with R 3.6 and ubuntu 16.04

### ISSUE THREAD

**Issue by mortisflux** [josephguillaume/hydromad#143]
# Issue: R CMD check failing with R 3.6 and ubuntu 16.04

## Issue summary:

R CMD check (without optional packages) on ubuntu 16.04 with R 3.6 returns the following:

```
   > test_check("hydromad")
  ── 1. Failure: formula works within functions (@test-statistics.R#81)  ─────────
  (time.formula[3] - time.fun[3])/time.fun[3] is not strictly less than 0.1. Difference: 0.0127
```

[https://github.com/josephguillaume/hydromad/runs/940399013?check_suite_focus=true](https://github.com/josephguillaume/hydromad/runs/940399013?check_suite_focus=true)

This doesn't seem to be misbehaving with R 4.0 or on Windows/Mac, so it seems to be an R 3.6 issue.

**Comment by jnothman** [comment]
That test is reliant on timings, so rather than being platform dependent, it could possibly fail on any system due to variability...

https://github.com/josephguillaume/hydromad/blob/master/tests/testthat/test-statistics.R#L79-L81

It might be appropriate to either:
* increase the threshold here to allow for some variation (maybe 15%)
* only run this tests if an environment variable is set, and disable that variable on CI

**Comment by josephguillaume** [comment]
Disabling this test in CI sounds good (and having a general mechanism to do so)

Though there seems to be something funny with the message: "is not strictly less than 0.1. Difference: 0.0127"
0.1 is less than 0.1...

**Comment by jnothman** [comment]
Difference between `(time.formula[3] - time.fun[3]) / time.fun[3]` and `0.1` is 0.0127.

**Comment by mortisflux** [comment]
> That test is reliant on timings, so rather than being platform dependent, it could possibly fail on any system due to variability...

Makes sense, which is why the test passed when I updated the roxygen2_documentation_v2 branch yesterday.

[https://github.com/josephguillaume/hydromad/runs/944765224?check_suite_focus=true](https://github.com/josephguillaume/hydromad/runs/944765224?check_suite_focus=true)


> Disabling this test in CI sounds good (and having a general mechanism to do so)

Skipping tests are usually done within the `test_that` blocks themselves. Adding a `skip('skip')` before this line is a simple solution, though we can also look into `skip_on_ci()`.

[https://rdrr.io/cran/testthat/man/skip.html](https://rdrr.io/cran/testthat/man/skip.html)

**Comment by josephguillaume** [comment]
I would prefer for it to be skipped only on ci, so that running the tests locally still causes a failure, but happy to accept a temporary fix+issue if needed.
