### ISSUE TITLE
warning messages from data("Cotter")

### ISSUE THREAD

**Issue by bunmalik** [josephguillaume/hydromad#146]
Cotter.rda seems to give the warnings below and end up with NA entries, I suspect its a bug

> data("Cotter")
Warning messages:
1: In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former
2: In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former

**Comment by WillemVervoort** [comment]
I can confirm this is a problem on R 4.02 (my laptop), but not on R 4.01 (my desktop). Is this an R base problem?
But my package on 4.01 is from 2018-07-01, so maybe it is the last hydromad build? I can reinstall?
> R.Version()
$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "4"

$minor
[1] "0.1"

$year
[1] "2020"

$month
[1] "06"

$day
[1] "06"

$`svn rev`
[1] "78648"

$language
[1] "R"

$version.string
[1] "R version 4.0.1 (2020-06-06)"

$nickname
[1] "See Things Now"

> packageDescription("hydromad")
Package: hydromad
Version: 0.9-26
Date: 2018-07-01
Title: Hydrological Model Assessment and Development
Author: Felix Andrews <felix@nfrac.org>, Joseph Guillaume <josephguillaume@gmail.com>
Maintainer: Joseph Guillaume <josephguillaume@gmail.com>
Description: A modelling framework for environmental hydrology: water balance accounting
          and flow routing in spatially aggregated catchments.  It supports simulation,
          estimation, assessment and visualisation of flow response to time series of
          rainfall and other drivers. Includes models (such as IHACRES CMD, Sacramento),
          transfer function estimators (including SRIV - Simplified Refined Instrumental
          Variable), etc.
Depends: R (>= 2.5.0), zoo (>= 1.6-3), lattice (>= 0.19-11), latticeExtra (>= 0.6-14),
          polynom, reshape
Imports: car (>= 2.0-2), Hmisc, stats, utils, Rcpp (>= 0.12.17)
Suggests: DEoptim, mgcv, chron, testthat, mco, cmaes, ppso,
          sensitivity,ggplot2,rsm,parallel,foreach,doRedis,ff,dream,playwith
LinkingTo: Rcpp
License: GPL (>= 2)
URL: http://hydromad.catchment.org/
Built: R 4.0.1; x86_64-w64-mingw32; 2020-06-30 03:35:17 UTC; windows

-- File: C:/Users/rver4657/Documents/R/win-library/4.0/hydromad/Meta/package.rds

**Comment by WillemVervoort** [comment]
I can confirm that reinstallation creates a problem. This is the same 0.9-26 according to the description, but my old installation was from 30-06-2020. So it must have happened after this. Possibly commit #c26c5ec ? updating to usethis::use_data?

> data(Cotter)
Warning message:
In data(Cotter) : data set ‘Cotter’ not found
> data(Canning)
Warning message:
In data(Canning) : data set ‘Canning’ not found
> data(Murrindi)
Warning message:
In data(Murrindi) : data set ‘Murrindi’ not found

**Comment by mortisflux** [comment]
I think this should be fixed once #126 is accepted. R CMD check gave warnings to do with not loading data sets properly (in later releases but not in 3.6), however, the error is no longer present after adding `Lazydata: true` to `Description`.

**Comment by WillemVervoort** [comment]
As a work around, users can follow the instructions in the appendix of the [tutorial](http://hydromad.catchment.org/downloads/tutorial.pdf) to create their own data set

**Comment by josephguillaume** [comment]
This is now fixed in https://github.com/josephguillaume/hydromad/tree/oldstable and I've uploaded it to the repo.
It can now be installed with

> options("repos"=c(options("repos"),hydromad="http://hydromad.catchment.org"))
> install.packages("hydromad")

**Comment by josephguillaume** [comment]
@joelnothman - is there any way I can record that the current 0.9-26 is actually on the oldstable branch and not the one that is tagged on master?

**Comment by jnothman** [comment]
Do you mean that the current tag is incorrect? You might need to delete the tag (or write over it with `git tag -f`).

**Comment by josephguillaume** [comment]
The tag was correct, but I had to make some additional commits, which I've made in a new 'oldstable' branch
I'm not yet comfortable publishing the current repo.
I suppose the simplest option is to delete the tag and just not have a 0.9-26 listed at all.
