### ISSUE TITLE
Add codecov.io badge to README

### ISSUE THREAD

**Issue by josephguillaume** [josephguillaume/hydromad#155]
codecov account is here:
https://codecov.io/gh/josephguillaume/hydromad

Not sure what badges are available - open to suggestions

**Comment by jnothman** [comment]
visit https://shields.io/; find all the badges you want.

**Comment by josephguillaume** [comment]
Added default badge from codecov.io in https://github.com/josephguillaume/hydromad/commit/5a42d97c9791895826bcb68280158d8acb1cda3c
