### ISSUE TITLE
Website for hydromad seems to be broken?

### ISSUE THREAD

**Issue by gdmcdonald** [josephguillaume/hydromad#168]
"Server Not Found" when trying to access http://hydromad.catchment.org/

<img width="435" alt="Screen Shot 2020-12-02 at 4 30 50 pm" src="https://user-images.githubusercontent.com/20785842/100832424-f3dfef00-34bb-11eb-9776-d9b5ece81d58.png">

**Comment by josephguillaume** [comment]
Thanks for getting in touch. Yes - we're having some issues with a forced migration of the server.
In the mean time, the help files are available in R and the package can be installed from github, with the latest release here: https://github.com/josephguillaume/hydromad/releases/tag/0.9-26
Do let us know if you have issues accessing anything particular while we sort out the situation with the server...

**Comment by josephguillaume** [comment]
Should be back up now - let us know if there any issues. Thanks!
