### ISSUE TITLE
Add HBV model to hydromad

### ISSUE THREAD

**Issue by buzacott** [josephguillaume/hydromad#46]
Add the HBV R/RCPP model code I have to be integrated to the hydromad package

**Comment by josephguillaume** [comment]
Ready when you are for this one. Let me know if you need any help/need to discuss anything before making a PR.

**Comment by josephguillaume** [comment]
I've just noticed there's HBV implementations in TUWmodel and HBV.IANIGLA, both on CRAN. Would it be possible to do a comparison of outputs/features with each of these?
I'll still want to include your implementation, but just want to be clear about differences with these others.
