### ISSUE TITLE
git tag past releases

### ISSUE THREAD

**Issue by jnothman** [josephguillaume/hydromad#49]
I noticed that the repository doesn't have any versions tagged, which can make it hard to identify which code corresponds to past releases.

I've identified the commits where the version in DESCRIPTION has changed.

| Commit  | Version |
| ------- | ------- |
| c6689fa | 0.9-26 |
| 3803442 | 0.9-25 |
| b8f706c | 0.9-24 |
| dab60ba | 0.9-23 |
| ebd8586 | 0.9-22 |
| e191999 | 0.9-20 |
| 235ce81 | 0.9-19 |
| be1cc4e | 0.9-18 |
| 48980fb | 0.9-17 |
| 657d9ff | 0.9-16 |
| dee6a0b | 0.9-15 |
| fb6705a | 0.9-14 |
| 4c3b130 | 0.9-13 |
| a7f91b7 | 0.9-12 |
| 012f226 | 0.9-11 |
| 747a6de | 0.9-9 |
| e2dd1bc | 0.9-8 |
| afeb500 | 0.9-7 |
| efaf793 | 0.9-6 |
| 35e7034 | 0.9-5 |
| 90beb2e | 0.9-4 |
| 4a144c3 | 0.9-3 |
| fab29d7 | 0.9-2 |
| cb248eb | 0.9-1 |
| 54b75f1 | 0.9-0 |
| fe658b7 | 0.8-7 |
| 8791d8d | 0.8-6 |
| 69affac | 0.8-5 |
| 4ca7089 | 0.8-4 |
| 78f4456 | 0.8-3 |
| d0eb5c1 | 0.8-2 |
| 61446ea | 0.8-1 |
| 897583a | 0.8-0 |
| 0372fa1 | 0.7-3 |
| 57e3311 | 0.7-2 |
| 6aeacd7 | 0.7-1 |
| 0809b7c | 0.7-0 |
| f8e2570 | 0.6-7 |
| d8bbe14 | 0.6-6 |
| eb99ce4 | 0.6-5 |
| b69435e | 0.6-4 |
| dd5fada | 0.6-3 |
| e93b638 | 0.6-2 |
| 91e1c0c | 0.6-1 |
| 4dc08c8 | 0.6-0 |
| f641c61 | 0.5-4 |
| bc0ca87 | 0.5-3 |
| f0e5c76 | 0.5-2 |

Would you like to git tag some or all of these? Code to do so can be generated.

Although: it's not clear to me what convention is being followed:
* do you bump the version to indicate the start of working on that version? or
* do you bump the version to release that version?

In other projects, release involves:
1. Remove the `.dev0` suffix from the version number
2. Commit (to master or to a release branch) and tag as a release
3. Bump the version, appending the `.dev0` suffix, commit to master.

(Ping @mortisflux fyi)

**Comment by josephguillaume** [comment]
I haven't had a consistent release process but have bumped the version number when uploading a new version to the hydromad.catchment.org repository, i.e. for each release.
We probably need to work out some rules on when to do a release.
Adding tags sounds useful if it's easy for you to set up. Thanks!

**Comment by jnothman** [comment]
Not really something you can do by forking and branching, so I can't do that. You can create your tags in your working copy with the below, then `git push --tags` to upload them to github.
```sh
git tag 0.9-26 c6689fa
git tag 0.9-25 3803442
git tag 0.9-24 b8f706c
git tag 0.9-23 dab60ba
git tag 0.9-22 ebd8586
git tag 0.9-20 e191999
git tag 0.9-19 235ce81
git tag 0.9-18 be1cc4e
git tag 0.9-17 48980fb
git tag 0.9-16 657d9ff
git tag 0.9-15 dee6a0b
git tag 0.9-14 fb6705a
git tag 0.9-13 4c3b130
git tag 0.9-12 a7f91b7
git tag 0.9-11 012f226
git tag 0.9-9 747a6de
git tag 0.9-8 e2dd1bc
git tag 0.9-7 afeb500
git tag 0.9-6 efaf793
git tag 0.9-5 35e7034
git tag 0.9-4 90beb2e
git tag 0.9-3 4a144c3
git tag 0.9-2 fab29d7
git tag 0.9-1 cb248eb
git tag 0.9-0 54b75f1
git tag 0.8-7 fe658b7
git tag 0.8-6 8791d8d
git tag 0.8-5 69affac
git tag 0.8-4 4ca7089
git tag 0.8-3 78f4456
git tag 0.8-2 d0eb5c1
git tag 0.8-1 61446ea
git tag 0.8-0 897583a
git tag 0.7-3 0372fa1
git tag 0.7-2 57e3311
git tag 0.7-1 6aeacd7
git tag 0.7-0 0809b7c
git tag 0.6-7 f8e2570
git tag 0.6-6 d8bbe14
git tag 0.6-5 eb99ce4
git tag 0.6-4 b69435e
git tag 0.6-3 dd5fada
git tag 0.6-2 e93b638
git tag 0.6-1 91e1c0c
git tag 0.6-0 4dc08c8
git tag 0.5-4 f641c61
git tag 0.5-3 bc0ca87
git tag 0.5-2 f0e5c76
```

**Comment by josephguillaume** [comment]
Done. Thanks!
