### ISSUE TITLE
Create a README for hydromad

### ISSUE THREAD

**Issue by WillemVervoort** [josephguillaume/hydromad#54]
# Issue:

A README for hydromad
## Issue summary:

The hydromad repository is missing a README (frontpage) to help users and developers understand the nature of the package and how to contribute. 
## Expected Behavior

The README should appear under the first code page in the repository: https://github.com/josephguillaume/hydromad
## Current Behavior

There is no README
## Possible Solution

Create a README
## Steps to Reproduce (for bugs)

1. https://github.com/josephguillaume/hydromad
2.
3.
4.

## Context

Helping other developers and users of the Hydromad repository better understand its aim and how to contribute
## Your Environment

NA

**Comment by josephguillaume** [comment]
Done. Thanks Willem!
