### ISSUE TITLE
Revisit website design

### ISSUE THREAD

**Issue by josephguillaume** [josephguillaume/hydromad#58]
* Some usability and browser compatibility issues reported
* "Looks dated"

Suggested tools for showing R documentation:
* R websites/markdown (https://rspatial.org/raster/index.html)
* Read the Docs https://docs.readthedocs.io/en/stable/ e.g. https://wflow.readthedocs.io/en/latest/ 
* https://pkgdown.r-lib.org/
* https://bookdown.org/yihui/blogdown/
* Hugo for static website generation: https://gohugo.io/ https://github.com/gohugoio/hugo

A generic site would make it easier/more familiar for people to use

**Comment by josephguillaume** [comment]
I'm also keen to showcase analysis flows that require more than one function (e.g. https://github.com/josephguillaume/hydromad/blob/master/demo/sensitivity.R) and that use models from other packages (e.g. `fuse`). 
Either these things need to be incorporated into the package API, or the website will need to go beyond documenting the API itself.

**Comment by jnothman** [comment]
> Either these things need to be incorporated into the package API, or the website will need to go beyond documenting the API itself.

This stuff also sounds admissable to a vignette

**Comment by WillemVervoort** [comment]
I agree, I am keen on building vignettes from our older teaching materials

**Comment by buzacott** [comment]
Here is a quick mockup I did in Bookdown, which is all Rmarkdown based. Could serve doubly as a vignette as html based vignettes are possible. Would be easy to demonstrate hyromad inside the document.

<img width="1343" alt="Screen Shot 2020-06-25 at 19 35 44" src="https://user-images.githubusercontent.com/26240158/85695194-26223f00-b71b-11ea-9dd3-9ba50d5ca219.png">

**Comment by mortisflux** [comment]
@buzacott looking good! And if you're not content with the default theme, there are [plenty](https://github.com/pzhaonet/bookdownplus) of [others](https://github.com/bookdown/Bookdown.Themes) to choose from.

**Comment by josephguillaume** [comment]
@buzacott - that does look promising. Thanks!

What does the documentation for a single function look like?

Given you've already gone so far, do you think you could make a PR with a content-complete version of the existing website, replacing the existing web/ folder?
Let me know if you need me to talk through how the existing website generation works.

It now also occurs to me that the website generation relies on .Rd files being available, so we'll need to double check it/it's replacement still works after moving to roxygen.

**Comment by jnothman** [comment]
One solution is also to build the HTML docs in CI and deploy them to a GitHub pages branch; or to have a service like readthedocs build them whenever a push is made here. Either way they will be able to extract the `Rd`

**Comment by WillemVervoort** [comment]
I think the issue here is that we want to retain the domain name for website, so unless we can get the github pages to display the hydromad.catchment.org it is not doable that way. Or we need set up a whole bunch of redirects. I also don't know the website backend, but I assume Joseph loads up the Rd files to the webdomain (with the releases).

**Comment by josephguillaume** [comment]
I agree extracting `Rd` won't be difficult - just need to adjust the workflow accordingly.

Ownership of the domain name is a little complicated, but the subdomain could in principle be redirected. The CRAN-style repository would need to be replicated at the new location though.

Yes, I just upload static files to the web server.

**Comment by buzacott** [comment]
> @buzacott - that does look promising. Thanks!
> 
> What does the documentation for a single function look like?
> 
> Given you've already gone so far, do you think you could make a PR with a content-complete version of the existing website, replacing the existing web/ folder?
> Let me know if you need me to talk through how the existing website generation works.
> 
> It now also occurs to me that the website generation relies on .Rd files being available, so we'll need to double check it/it's replacement still works after moving to roxygen.

roxygen still populates the man folder with Rd files. Yep I can look into replacing the existing web folder with a PR. I haven't attempted to integrate the Rd files into bookdown, I'll need to see how that is done.

**Comment by josephguillaume** [comment]
> I haven't attempted to integrate the Rd files into bookdown, I'll need to see how that is done.

Up to you - that would still be a major step, so don't feel obliged. 

It would be important for that kind of content to be automatically populated though - we don't want to have to manually propagate those changes.

**Comment by buzacott** [comment]
After exploring this a bit I think pkgdown (https://pkgdown.r-lib.org) might be the way to go. It compiles all the R documentation and you can include vignettes and tutorials.

**Comment by buzacott** [comment]
Super easy

<img width="1072" alt="Screen Shot 2020-06-27 at 16 23 20" src="https://user-images.githubusercontent.com/26240158/85916290-bb940f00-b892-11ea-864a-2ad9821da1f9.png">

<img width="1072" alt="Screen Shot 2020-06-27 at 16 23 23" src="https://user-images.githubusercontent.com/26240158/85916295-c6e73a80-b892-11ea-945e-277347918ba4.png">

<img width="1072" alt="Screen Shot 2020-06-27 at 16 24 36" src="https://user-images.githubusercontent.com/26240158/85916296-c8b0fe00-b892-11ea-8edc-72f74ac615a8.png">

Custom work flows and tutorials can go under articles. The homepage can be customised to be something else, by default it reads the ReadMe in the Git home dir. I replicated the documentation locations as per the current website under Reference (you can pick which functions appear there), however it seems to be linking to other functions which I'll need to examine.

**Comment by josephguillaume** [comment]
Looks familiar :-P, which is obviously a good thing for usability.
Please do PR the generation code when ready. We obviously still need to check that everything from the old website is still possible, but this does seem the way to go.

**Comment by josephguillaume** [comment]
One idea would be to have a gallery of analysis outputs (text and figures) to browse through. I assume we could do this with a vignette-style document

**Comment by buzacott** [comment]
I've managed to replicate the functionality of the existing website quite well.

I've structured it as follows:

- Home page is the GitHub ReadMe
- Get started is the existing website home page
- Installation page isn't featured as instructions are included on the home page from the readme
- Reference matches the layout of the existing side bar structure "modelling framework" "assessment" and so on. The website has some references to functions I couldn't find and I've commented them out in `_pkgdown.yml`. When the website is built it also finds some functions that are not currently placed in any of the sections
- No articles currently, except for `hydromad.Rmd` which is automatically converted to the Get Started page
- Converted the NEWS file to NEWS.md for the News/Changelog page

Anything else you would like? Otherwise I'll submit a PR

Changes are at: https://github.com/buzacott/hydromad/tree/pkgdown. The main structure is visible in the _pkgdown.yml

**Comment by josephguillaume** [comment]
Sounds pretty good. Thanks!
I think I'd need to see it to know what is missing, so go ahead with a PR.
We ideally would want to include the current vignette, given it is available, but it's not currently building (#36), so it's ok to leave out for the moment

**Comment by buzacott** [comment]
One thing to be aware of is that pkgdown will fail to include images in the articles if there are any spaces in the full path, at least on macOS/ubuntu. I was having issues as my `hydromad` folder is located in ~/Dropbox (Sydney Uni)/...

https://github.com/r-lib/pkgdown/issues/1218

**Comment by josephguillaume** [comment]
pkgdown version merged in https://github.com/josephguillaume/hydromad/pull/109
New issues can be raised for further improvements to the new website before release for hydromad 1.0
