### ISSUE TITLE
Deal with 'library' or 'require' calls in package code

### ISSUE THREAD

**Issue by josephguillaume** [josephguillaume/hydromad#61]
CRAN policy does not permit 'library' or 'require' calls in package code.

We load 'ff' 'ggplot2' 'parallel' 'playwith'

Instructions in R CMD CHECK say:
> Please use :: or requireNamespace() instead.
> See section 'Suggested packages' in the 'Writing R Extensions' manual.

Need to select a policy for dealing with suggested packages in hydromad.

**Comment by josephguillaume** [comment]
https://r-pkgs.org/namespace.html
`Use requireNamespace("x", quietly = TRUE) inside a package if you want a specific action (e.g. throw an error) depending on whether or not a suggested package is installed.`

**Comment by WillemVervoort** [comment]
@josephguillaume Some of this might be in my code, you want me to pick this one up?

**Comment by josephguillaume** [comment]
It's my code too - we need a hydromad-wide solution. Could you look into how the `requireNamespace` process works?
You can probably go straight into a PR for one or more of these places, if you're up for it? Just working through a case would be very helpful to get our head around what the "right" approach is.

**Comment by WillemVervoort** [comment]
This might in fact need a bit more discussion. From a maintenance perspective requireNamespace is probably the easiest solution as this is only one line of code to change. (But we might need to map where we use this in all the code for maintenance).
However, the danger is that this inadvertently messes up other code as there might be overlapping names with code. So the strongest solution would be to use  "::", but this is also a lot of work as we will need to find all the package specific code. 

So for a package wide solution I am not sure.
You have already use requireNamespace() (paretoObjectivesNsga2.R) and also have used require() (paretoObjectivesVaryWeights)

Any suggestions, I think we really should use ::

**Comment by josephguillaume** [comment]
Lol. Thanks for pointing out my poor memory and inconsistent coding.
So if I understand correctly, requireNamespace is just about adding explicit error handling if a suggested package is used.
https://github.com/josephguillaume/hydromad/blob/master/R/paretoObjectivesNsga2.R#L4

What happens with :: if the suggested package is missing? Is the error message meaningful enough without the explicit requireNamespace?
Is your preference for :: because it's more explicit about avoiding symbol name conflicts?

**Comment by josephguillaume** [comment]
Actually, does the tidyverse style guide include a point about this?

**Comment by WillemVervoort** [comment]
From the '::' help file:

**The package namespace will be loaded if it was not loaded before the call, but the package will not be attached to the search path.

Specifying a variable or package that does not exist is an error.**

I can't find anything in the tidyverse style guide, I will check the write R extensions doc

**Comment by WillemVervoort** [comment]
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-namespaces

Essentially the recommendation is to declare as much as possible in NAMESPACE. and only in some cases use ::

**If a package only needs a few objects from another package it can use a fully qualified variable reference in the code instead of a formal import. A fully qualified reference to the function f in package foo is of the form foo::f. This is slightly less efficient than a formal import and also loses the advantage of recording all dependencies in the NAMESPACE file (but they still need to be recorded in the DESCRIPTION file). Evaluating foo::f will cause package foo to be loaded, but not attached, if it was not loaded already—this can be an advantage in delaying the loading of a rarely used package.**

**Comment by josephguillaume** [comment]
So require attaches the package and :: doesn't? That's certainly helpful to avoid name collisions.

**Comment by WillemVervoort** [comment]
Yes, that is the idea
Willem

**Comment by josephguillaume** [comment]
Let's go with :: throughout hydromad for functions from suggested packages.
It seems the error is that "there is no package named X", which is not as helpful as my beautiful "package mco is required for paretoObjectivesNsga2" but simpler and with other benefits

**Comment by josephguillaume** [comment]
@WillemVervoort - if you're still happy to deal with this, perhaps you can assign yourself?

**Comment by WillemVervoort** [comment]
How do I do that? I don't see an option. Also, it is slightly more complex. If the package is not in your library folder you cannot use ::
So for dream and ppso which need to be installed from devtools, this maybe needs more thought.

**Comment by josephguillaume** [comment]
Probably only I can assign at the moment.
Yes - if you try to :: a package that isn't installed, it raises an error - that's the desired behaviour

**Comment by WillemVervoort** [comment]
OK, this needs a bit more discussion. I had a look at which files use "require" or "library", and only looking at R files. 
There are a bunch of files in the data directory that probably convert raw data to the desired hydromad zoo format that use library(). I assume I can ignore all these as Writing R extensions says:
"OK if that conditioning is done in examples/tests/vignettes"
Similarly there are files in "demo" for which the above also applies.
So I will concentrate first just on those R scripts that are in the "R" folder

**Comment by josephguillaume** [comment]
Yeah, just the R folder would be right.
We'd have to look at many of the fitBy functions too - I'm not sure if they're currently using library or are actually listed in namespace?

**Comment by WillemVervoort** [comment]
I went through a few of these, but in some requireNamespace() is totally appropriate (see for example [event.xyplot.hydromad.R](https://github.com/WillemVervoort/hydromad/blob/Require/R/event.xyplot.hydromad.R)), but in others it can be removed as you already use "::".

I will definitely fix all the require() or library()

**Comment by josephguillaume** [comment]
Good point - that's a case where the package is required by a package outside hydromad, so "::" doesn't work.
Are we saying that "::" should be used in all other cases?

**Comment by WillemVervoort** [comment]
Yes, that is what I will try to implement.
