### ISSUE TITLE
Suppress errors about R-devel in standard-ci?

### ISSUE THREAD

**Issue by josephguillaume** [josephguillaume/hydromad#82]
> unable to access index for repository https://cloud.r-project.org/bin/macosx/contrib/4.1

R-devel does install successfully - the error doesn't seem to be an issue.

> sudo installer -pkg /Users/runner/runners/2.263.0/work/_temp/R-devel.pkg -target /. installer: Package name is R 4.1.0 for macOS. installer: The install was successful.

and there's a line under R CMD Check in the logs that states:

> * using R Under development (unstable) (2020-06-21 r78727)

**Comment by mortisflux** [comment]
I'm not sure whether there is anything we need to do about this. This pops up under "Query dependencies", which is a task that successfully completes irrespective of this warning message. 

If you look at this same GitHub action for the [tidyverse](https://github.com/tidyverse/dplyr/runs/827827037?check_suite_focus=true), you'll notice they have the same problem!

**Comment by josephguillaume** [comment]
Yeah, it would be just to remove a useless annotation.
I should add a label for issues that are just out of perfectionism. Or should we add a project for issues that sih is/will work on?

**Comment by josephguillaume** [comment]
Addressed by disabling in #153 . New issue added: #127
