### ISSUE TITLE
Run styler on full package

### ISSUE THREAD

**Issue by josephguillaume** [josephguillaume/hydromad#85]
Submit as PR to check whether some styler settings need to be tweaked.
Will address many styler and linter errors.

**Comment by josephguillaume** [comment]
@mortisflux to do?

**Comment by josephguillaume** [comment]
Actually, was this just going to involve doing `styler::style_pkg()`? If so, I could probably do it given I'll want to check what it does to the code afterwards and it's a blocking change for the R code.

**Comment by mortisflux** [comment]
> Actually, was this just going to involve doing `styler::style_pkg()`? If so, I could probably do it given I'll want to check what it does to the code afterwards and it's a blocking change for the R code.

Yup, `styler::style_pkg()` is used to style all the source code of the package in one go, whilst `styler::style_file()` is the command to style a single file. I'd recommend running the latter command locally on a couple of files at least to make sure you're happy with the output before applying `styler::style_pkg()`.
