### ISSUE TITLE
R_styler fails on push

### ISSUE THREAD

**Issue by josephguillaume** [josephguillaume/hydromad#95]
R_styler runs on push and pull request but the workflow is currently dependent on being in a pull request:
```
 Run r-lib/actions/pr-fetch@master0s
##[error]Empty value for parameter 'pull_number': undefined
Run r-lib/actions/pr-fetch@master
Collecting information about PR #undefined...
##[error]Empty value for parameter 'pull_number': undefined
```

https://github.com/josephguillaume/hydromad/blob/master/.github/workflows/R_styler.yaml#L23

Could obviously just run on pull request, but it would be nice for contributors to get feedback before opening a PR?

**Comment by josephguillaume** [comment]
Or maybe it should just not run on push, because a user can push further commits to an open PR anyway

**Comment by jnothman** [comment]
I'd suggest automatic formatting to be implemented as a pre-commit hook rather than something done in CI.

**Comment by jnothman** [comment]
See https://lorenzwalthert.github.io/precommit/ for example

**Comment by josephguillaume** [comment]
R_styler is now just a check for PRs. User is responsible for styling locally (e.g. with RStudio add-in), and we can plan a pre-commit hook to potentially help with that.
